return {
	"nvimdev/dashboard-nvim",
	event = "VimEnter",
	config = function()
		require("dashboard").setup({
			theme = "doom",
			config = {
				header = {
					"                                         ",
					"  ██╗  ██╗ ██████╗  ██████╗ ██╗     ██╗  ",
					"  ██║  ██║██╔═══██╗██╔═══██╗██║     ██║  ",
					"  ███████║██║   ██║██║   ██║██║     ██║  ",
					"  ██╔══██║██║   ██║██║   ██║██║     ██║  ",
					"  ██║  ██║╚██████╔╝╚██████╔╝███████╗██║  ",
					"  ╚═╝  ╚═╝ ╚═════╝  ╚═════╝ ╚══════╝╚═╝  ",
					"                                         ",
					"                                         ",
				},
				center = {
					{
						icon = "📄 ",
						icon_hl = "Title",
						desc = "New File           ",
						desc_hl = "String",
						key = "n",
						keymap = "n",
						key_hl = "Number",
						action = "enew",
					},
					{
						icon = "🌴 ",
						icon_hl = "Title",
						desc = "Open File Tree     ",
						desc_hl = "String",
						key = "e",
						keymap = "e",
						key_hl = "Number",
						action = ":Yazi",
					},
					{
						icon = "📁 ",
						icon_hl = "Title",
						desc = "Open File          ",
						desc_hl = "String",
						key = "o",
						keymap = "o",
						key_hl = "Number",
						action = "edit .",
					},

					{
						icon = "👨‍🎨 ",
						icon_hl = "Title",
						desc = "Lazy Plugin Manager",
						desc_hl = "String",
						key = "l",
						keymap = "SPC l",
						key_hl = "Number",
						action = "Lazy",
					},
					{
						icon = "🚪 ",
						icon_hl = "Title",
						desc = "Quit               ",
						desc_hl = "String",
						key = "q",
						keymap = "SPC q",
						key_hl = "Number",
						action = "qa",
					},
				},
				footer = {
					"",
					"🔥 Happy Coding with Hooli Setup! 🔥",
				},
			},
		})
	end,
	dependencies = { { "nvim-tree/nvim-web-devicons" } },
}
